import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: [  '100','200', '300','400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Dashboard Car",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-white`}>{children}</body>
    </html>
  );
}
